language: android
android:
  components:
    - build-tools-22.0.1 # Specify your build tools verison
    - android-22 # Android Platform Target
env: # Envirement Variables
global:
before_install:
# Commands to excecute before install
- echo "Before install stage"
install:
# Specify what and how to install
- echo "Install stage"
- sudo apt-get install -y python-software-properties
- curl --silent --location https://deb.nodesource.com/setup_0.12 | sudo bash -
- sudo apt-get install -y nodejs libsass
- sudo npm install
before_script:
# Commands to excecute before running tests
- echo "Before script stage"
script:
- echo "Starting build"
- npm run compile 
