language: android
android:
  components:
    - build-tools-22.0.1 # Specify your build tools verison
    - android-22 # Android Platform Target

before_install:
# Commands to excecute before install
- echo "Before install stage"
install:
# Specify what and how to install
- echo "Install stage"
- sudo apt-get install -y python-software-properties
- sudo npm install
before_script:
# Commands to excecute before running tests
- echo "Before script stage"
script:
- echo "Starting build"
- gulp compile 
